    - name: Python | install python-pip
      apt: name=python-pip update_cache=yes state=latest
      become: yes
      tags:
        -setup
        -python

    - name: Python | Update pip
      shell: pip install -U pip
      become: yes
      tags:
        -setup
        -python

    - name: Python | install python-dev
      apt: name=python-dev update_cache=yes state=latest
      become: yes
      tags:
        -setup
        -python
