---
  - name: Configuration | install python mysql connector
    pip: name=MySQL-python state=present
    become: yes
    tags:
      - mysql

  - name: Configuration | Create databases
    mysql_db:
      name: "{{ item.name }}"
      collation: "{{ item.collation | default('utf8_general_ci') }}"
      encoding: "{{ item.encoding | default('utf8') }}"
      state: present
      login_host: "{{mysql_host | default('localhost')}}"
      login_user: "{{mysql_root_user | default('root')}}"
      login_password: "{{mysql_root_password | default('devroot')}}"
    with_items: "{{ mysql_databases | default([]) }}"
    tags:
      - mysql

  - name: Configuration | Create users
    mysql_user:
      name: "{{ item.name }}"
      host: "{{ item.host | default('localhost') }}"
      password: "{{ item.password }}"
      priv: "{{ item.priv | default('*.*:USAGE') }}"
      state: "{{ item.state | default('present') }}"
      append_privs: "{{ item.append_privs | default('no') }}"
      login_host: "{{mysql_host | default('localhost')}}"
      login_user: "{{mysql_root_user | default('root')}}"
      login_password: "{{mysql_root_password | default('devroot')}}"
    with_items: "{{ mysql_users | default([]) }}"
    no_log: true
    tags:
      - mysql
