---
  # Parameters:
  #  mysql_root_password

  - name: MySQL | Check if is installed
    command: test -x /usr/bin/mysql
    when: ansible_system == "Linux"
    register: mysql_present
    ignore_errors: yes
    tags:
      - mysql

  - name: MySQL | Preset root password
    shell: echo mysql-server-5.5 mysql-server/{{item}} password {{mysql_root_password}} | debconf-set-selections
    when: ansible_os_family == "Debian" and mysql_present|failed
    with_items:
      - "root_password"
      - "root_password_again"
    become: yes
    tags:
      - mysql


  - name: MySQL | Install
    apt: update-cache=yes force=yes state=present pkg=mysql-server
    when: ansible_os_family == "Debian" and mysql_present|failed
    become: yes
    tags:
      - mysql

  - name: MySQL | install libmysqlclient-dev
    apt: name=libmysqlclient-dev update_cache=yes state=latest
    when: ansible_os_family == "Debian" and mysql_present|failed
    become: yes
    tags:
      - mysql

  - name: MySQL | Restart
    service: name=mysql state=restarted
#    when: mysql_conf.changed
    when: docker_test is not defined
    become: yes
    tags:
      - mysql

