---
# tasks file for sa-php-apache

  - import_tasks: php_switchversion.yml

  - include_tasks: "php{{ php_recipy }}/main.yml"

  - include_tasks: tasks_xdebug.yml
    when: option_install_xdebug

  - include_tasks: "php_additional_extensions.yml"

  - include_tasks: tasks_composer.yml
    when: option_install_composer
