  - block:

    - name: PHP | Distribution defaults
      set_fact:
        php_version: "5.6"
        php_module_prefix: "php5.6"
        php_prefix: "php5.6"
        php_recipy: "5.6"
      when: ansible_distribution_release in ["trusty"]

    when:  php_family == "default"  or php_family == 5

  - block:

    - name: PHP | Fix php family prefix for 7
      set_fact:
        php_version: "7.0"
        php_module_prefix: "php7.0"
        php_prefix: "php7.0"
        php_recipy: "7.0"
      when: ansible_distribution_release in ["xenial"]

    - name: PHP | Fix php family prefix for 7
      set_fact:
        php_version: "7.2"
        php_module_prefix: "php7.2"
        php_prefix: "php7.2"
        php_recipy: "7.0"
      when: ansible_distribution_release in ["bionic"]

    when:  php_family == "default"  or php_family == 7

  - name: PHP | Fix php family prefix for 7.0
    set_fact:
      php_version: "7.0"
      php_module_prefix: "php7.0"
      php_prefix: "php7.0"
      php_recipy: "7.0"
    when: php_family == "7.0"
    tags:
      -php
      -setup

  - name: PHP | Fix php family prefix for 7.1
    set_fact:
      php_version: "7.1"
      php_module_prefix: "php7.1"
      php_prefix: "php7.1"
      php_recipy: "7.0"
    when: php_family == "7.1"
    tags:
      -php
      -setup

  - name: PHP | Fix php family prefix for 7.2
    set_fact:
      php_version: "7.2"
      php_module_prefix: "php7.2"
      php_prefix: "php7.2"
      php_recipy: "7.0"
    when: php_family == "7.1"
    tags:
      -php
      -setup

  - name: PHP | Fix php family prefix for 5.6
    set_fact:
      php_version: "5.6"
      php_module_prefix: "php5.6"
      php_prefix: "php5.6"
      php_recipy: "5.6"
    when: php_version == "5.6" or php_family == 5

  - name: PHP | Add apt repository for php 5.6
    apt_repository: repo='ppa:ondrej/php'
    when: php_version == "5.6" or php_family == 5
    become: yes
    tags:
      -php
      -setup

  - name: PHP | Default platform provided repository is used
    debug: msg="Default platform available debs will be used for php."
    when: (php_family is not defined) or (php_family == "default")
